MODULE_TOPDIR = ../..

SUBDIRS = \
	r.dispersal.neighbour \
	r.dispersal.kernel \
	r.dispersal.growth \
	r.dispersal.survival \
	r.dispersal.recruit \
	r.dispersal.filter.maxpop \
	r.dispersal.filter.class \
	r.dispersal.stats \
	r.dispersal.ros
		
include $(MODULE_TOPDIR)/include/Make/Dir.make

default: all

all: subdirs

clean: cleansubdirs
