MODULE_TOPDIR = ../..

SUBDIRS = \
	r.mdig.agepop \
	r.mdig.neighbour \
	r.mdig.kernel \
	r.mdig.growth \
	r.mdig.survival \
	r.mdig.recruit \
	r.mdig.filter.maxpop \
	r.mdig.filter.class \
	r.mdig.stats \
	r.mdig.ros \
	r.mdig.localspread \
        r.mdig.outliers
		
include $(MODULE_TOPDIR)/include/Make/Dir.make

default: all

all: subdirs

clean: cleansubdirs
