MODULE_TOPDIR = ../../..

PGM = r.mdig.ros

LIBES = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB)
DEPENDENCIES = $(DISPLAYDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make


default: cmd
